# Generated by Django 5.2.4 on 2025-08-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('shop_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('params', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parsing_requests',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('article', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=50, null=True)),
                ('tx1', models.CharField(blank=True, max_length=255, null=True)),
                ('tx2', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='parsing.request')),
            ],
            options={
                'db_table': 'parsing_results',
            },
        ),
    ]
